apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-microk8s-controller-nb2q6
data:
  client-body-timeout: "360"
  client-header-timeout: "360"
  proxy-connect-timeout: "360"
  proxy-read-timeout: "360"
  proxy-send-timeout: "360"
